POST http://localhost:8080/events/
content-type:application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MDk5MDkwNDYsInVzZXJJZCI6MX0.sjKXntkSJAe2iooULDKreGXTjGlqWl7rLsDt2jpX4t4

{
    "name":"Test event 5",
    "description":"test event5",
    "location":" A test location",
    "datetime":"2025-01-01T15:30:00.000Z"
}